//import NavBar from "../../components/navbar/NavBar";
import { useState } from "react";
import CatCarousel from "../../components/categories-carousel/CatCarousel";
import './home.css';

import ArrowBackIosIcon from '@mui/icons-material/ArrowBackIos';
import ArrowForwardIosIcon from '@mui/icons-material/ArrowForwardIos';
import { Button } from "@mui/joy";
import { Typography } from "@mui/material";

export default function Home() {

    //apply state for the quiz ad
    const [quizComplete, setQuizComplete] = useState(false);

    return (

        <div>
            <CatCarousel />
            <br />
            <div className="home-header">
                <h4 className="home-h4"> Let's Make Things a Little More Personal </h4>
                <p> Take our quick assesment for a better curated homepage </p>
                {/* <br /> */}
                <Button sx={{ background: 'linear-gradient(to bottom, #9CD393, #388E3C)', height: '25%'}}> <Typography fontFamily='Open Sans, sans-serif'> Take Assesment </Typography> </Button>
            </div>
            <br />
            <div>
                {/* post box here 
                REDESIGNING*/}
            </div>
            <div>
                {/* categories generated by user interest here */}
            </div>
            <div className="div" />
            <div>
               <p className="user-connect-p"> Meet, trade, connect with other creatives in your city </p> 
               <button className="arrow"> <ArrowBackIosIcon /> </button>
               {/* user info from dummy accounts here */}
               <button className="arrow"> <ArrowForwardIosIcon /> </button>
            </div>
        </div>
    )
}
